### ISSUE TITLE
Is this the RTL build ?

### ISSUE THREAD

**Issue by luzpaz** [moceap/scribus-test#1]
AKA https://build.opensuse.org/package/show/home:moceap/Scribus  ?

**Comment by moceap** [comment]
It's try to improve the patch on fresh version of Scribus.

**Comment by luzpaz** [comment]
@moceap what's the verdict ?

**Comment by moceap** [comment]
Yes, It's a try for that .

**Comment by luzpaz** [comment]
Did it succeed ?

**Comment by moceap** [comment]
In https://build.opensuse.org/package/show/home:moceap/Scribus partly succeeded, but here no.

I have lack of Logistics

**Comment by luzpaz** [comment]
What do you need help with ?
